app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/


// 不需要登录验证的路由
Route::get('/', ['as' => 'index','uses'=>'BlogController@index']);

Route::get('/article/{id}',['as'=>'blog.detail','uses'=>'BlogController@detail']);
Route::get('/tags/{uid}/{tag}',['as'=>'blog.detail','uses'=>'BlogController@tag']);

//用户登录
Route::get('user/login', ['as' => 'login', 'uses' => 'UserController@getLogin']);
Route::post('user/login', ['as' => 'login', 'uses' => 'UserController@postLogin']);

//用户注册
Route::get('user/register',['as'=>'register','uses'=>'UserController@getRegister']);
Route::post('user/register',['as'=>'register','uses'=>'UserController@postRegister']);

Route::get('blog/{username}',['as'=>'blog.user','uses'=>'BlogController@user']);
Route::get('blog/cate/{cid}',['as'=>'blog.cate','uses'=>'BlogController@cate']);
Route::get('achieve/{date}/{uid}',['as'=>'blog.achieve','uses'=>'BlogController@achieve']);




// 需要登录验证才能操作的接口
Route::group(array('before' => 'auth'), function()
{
    //退出
    Route::get('user/logout', ['as' => 'logout', 'uses' => 'UserController@getLogout']);

    //用户中心
    Route::get('user/home',['as'=>'home','uses'=>'UserController@home']);
    //修改用户信息
    Route::get('user/edit',['as'=>'user.edit','uses'=>'UserController@edit']);
    Route::post('user/postEdit',['as'=>'user.postEdit','uses'=>'UserController@postEdit']);

    //修改用户密码
    Route::get('user/pwd',['as'=>'user.pwd','uses'=>'UserController@pwd']);
    Route::post('user/chpwd',['as'=>'user.chpwd','uses'=>'UserController@chpwd']);

    //用户头像上传
    Route::get('user/pic', ['as' => 'user.pic', 'uses' => 'UserController@modifyPic']);
    Route::post('user/upload', ['as' => 'user.upload', 'uses' => 'UserController@upload']);
    Route::post('user/cutPic', ['as' => 'user.cutPic', 'uses' => 'UserController@cutPic']);


    //文章管理路由
    Route::resource('articles','ArticlesController');
    Route::get('articles/{id}/del',array('as'=>'articles.del','uses'=>'ArticlesController@destroy'));
    Route::get('search/{key?}','ArticlesController@search');

    //文章回车站管理
    Route::get('recycle',array('as'=>'articles.recycle','uses'=>'ArticlesController@recycle'));
    Route::get('recycle/{ids}/del',array('as'=>'articles.recycle.del','uses'=>'ArticlesController@realDelete'));
    Route::get('find/{key?}','ArticlesController@find');
    Route::post('ajaxEdit','ArticlesController@ajaxEdit');

    //文章分类管理路由
    Route::get('cate',array('as'=>'cate.index','uses'=>'CateController@index'));
    Route::get('cate/create',array('as'=>'cate.create','uses'=>'CateController@create'));
    Route::post('cate',array('as'=>'cate.store','uses'=>'CateController@store'));
    Route::get('cate/{id}/edit',array('as'=>'cate.edit','uses'=>'CateController@edit'));
    Route::put('cate/{id}',array('as'=>'cate.update','uses'=>'CateController@update'));
    Route::get('cate/{id}/del',array('as'=>'cate.del','uses'=>'CateController@destroy'));

});

app/models/Cate.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2015/1/12
 * Time: 10:18
 */
use Illuminate\Database;
class Cate extends Eloquent{
    protected $fillable = array('name', 'count','pid','uid','desc');
}

app/controllers/CateController.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2015/1/16
 * Time: 11:54
 */

class CateController extends BaseController{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $cate = Cate::where('uid',Auth::id())->paginate(5);//列出属于当前登录用户的文章分类
        return View::make('cate.index', compact('cate'));
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return View::make('cate.create');
    }

    /**
     * @create提交动作
     */
    public function store(){
        //数据验证
        //数据验证
        $rules = array(
            'name' => 'required|min:2',
            'desc'=>'required'
        );

        $validator = Validator::make(Input::all(), $rules);
        //规则校验
        if ($validator->fails())
        {
            return Redirect::route('cate.create')
                ->withErrors($validator)
                ->withInput();
        }
          //检查类名唯一性,不同用户的分类可以相同
            $name=Input::get('name');
            $num=Cate::where('name',$name)->where('uid',Auth::id())->count();
        if($num==0){
            //类别入库
            Cate::create(array(
                'name'=>Input::get('name'),
                'uid'=>Input::get('uid'),
                'desc'=>Input::get('desc')
            ));
            return Redirect::route('cate.create')->with('success', '添加成功！');
        }else{
            return Redirect::route('cate.create')->withInput()->with('error','类名不能重复');
        }

    }

    /**
     * @edit
     */

    public function  edit($id){
        $cate=Cate::find($id);
        if(count($cate)==0){
            return Redirect::route('cate.index')->with('error','分类不存在！');
        }

        //检查是否非法编辑，文章所有者是否一致
        if($cate->uid!==Auth::id()){
            return Redirect::to('user/login');
        }
        return View::make('cate.edit',compact('cate'));
    }

    /**
     * @update
     */

    public function update($id){
        //数据验证
        $rules=array(
            'name'=>'required|min:2',
            'desc'=>'required'
        );
        $validator=Validator::make(Input::all(),$rules);

        if($validator->fails()){
            Return Redirect::route('cate.edit',array('id'=>$id))->withErrors($validator)
                ->withInput();
        }

        //检查是否非法编辑，分类所有者是登录用户
        $cate=Cate::find($id);
        $uid=$cate->uid;//获取uid
        if($uid!=Auth::id()){
            return Redirect::to('user/login');
        }

        //检查修改的用户分类是否唯一
        $count=Cate::where('name',Input::get('name'))->where('uid',Auth::id())->where('id','<>',$id)->count();
        if($count==0){
            //执行更新操作
            $cate->name=Input::get('name');
            $cate->desc=Input::get('desc');
            $cate->save();
            return Redirect::route('cate.edit',array('id'=>$id))->with('success','修改成功！');
        }else{
            Return Redirect::route('cate.edit',array('id'=>$id))->with('error','分类不能重复！')
                ->withInput();
        }
    }

    /**
     * @destroy
     */

    public function destroy($id){

        //权限检查，检查是否非法编辑，分类所有者是登录用户
        $cate=Cate::find($id);
        $uid=$cate->uid;//获取uid
        if($uid!=Auth::id()){
            return Redirect::to('user/login');
        }

        //删除分类
        //Cate::find($id)->delete();//按实例删除
        Cate::destroy($id);//按住键删除

        //修改改分类所属文章状态为0，修改分类为默认值0【可选操作】
        Article::where('cid',$id)->update(array('cid'=>0,'status'=>0));

        return  Redirect::route('cate.index')->with('message','分类删除成功!');
    }

} 

app/views/cate/create.blade.php
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Laravel PHP Framework</title>
	 {{HTML::script('js/jquery.js')}}
	  {{HTML::script('js/navbar.js')}}
     {{HTML::script("js/cf.js")}}
     {{HTML::style("css/cate.css")}}
     {{ Ueditor::css() }}
      {{ Ueditor::content() }}
       <script>
           $(function(){
               //点击提示框消失
                   $(".success").click(function(){
                       $(this).fadeOut(2000);
                   });

                    $(".error").click(function(){
                                          $(this).fadeOut(2000);
                                      });

           })
           </script>
     {{ Ueditor::js() }}
     <script>
          var ue = UE.getEditor('desc');
     </script>
</head>
<body>
	<div class="main">
        <div class="top_nav">
               <div class="top_nav_l"><b class="index"></b> 网站后台 <span>/</span>{{link_to_route('cate.index','首页')}}<span>/</span>添加文章分类</div>
               <div class="top_nav_r"> {{link_to_route('logout','退出')}}</div>
               <div style="clear:both"></div>
        </div>

       <!--成功提示-->
                      @if(Session::has('success'))
                         <div class="success">{{Session::get('success')}}</div>
                         @endif
                 <!--错误提示-->
                      @if(Session::has('error'))
                         <div class="error">{{Session::get('error')}}</div>
                         @endif
	@include('navbar')
        <div class="content">
            <div class="form">
                {{Form::open(array('url'=>'cate','method'=>'post'))}}
                        <p class="input_txt"> <span>{{Form::label('标题：')}}</span> {{Form::text('name')}}</p>
                         <p class="input_txt"> <span>{{Form::label('desc','描述：')}}</span> {{Form::textarea('desc')}}</p>
                        <div>
                            {{Form::hidden('uid',Auth::id())}}
                            {{Form::submit('添加',array('class'=>'btn'))}}
                        </div>
                         <div class="clear"></div>
                    {{Form::close()}}
            </div>
        </div>
	</div>
</body>
</html>

app/views/cate/edit.blade.php
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Laravel PHP Framework</title>
	 {{HTML::script('js/jquery.js')}}
	 {{HTML::script('js/navbar.js')}}
     {{HTML::script("js/cf.js")}}
     {{HTML::style("css/cate.css")}}
     {{ Ueditor::css() }}
      {{ Ueditor::content() }}
       <script>
           $(function(){
               //点击提示框消失
                   $(".success").click(function(){
                       $(this).fadeOut(2000);
                   });

                    $(".error").click(function(){
                                          $(this).fadeOut(2000);
                                      });
           })
           </script>
     {{ Ueditor::js() }}
     <script>
          var ue = UE.getEditor('desc');
     </script>
</head>
<body>
	<div class="main">
        <div class="top_nav">
               <div class="top_nav_l"><b class="index"></b> 网站后台 <span>/</span>{{link_to_route('cate.index','首页')}}<span>/</span>分类编辑</div>
               <div class="top_nav_r"> {{link_to_route('logout','退出')}}</div>
               <div style="clear:both"></div>
        </div>

       <!--成功提示-->
                      @if(Session::has('success'))
                         <div class="success">{{Session::get('success')}}</div>
                         @endif
                 <!--错误提示-->
                      @if(Session::has('error'))
                         <div class="error">{{Session::get('error')}}</div>
                         @endif
	@include('navbar')
        <div class="content">
            <div class="form">
                {{Form::open(array('route'=>array('cate.update',$cate->id),'method'=>'put'))}}
                        <p class="input_txt"> <span>{{Form::label('标题：')}}</span> {{Form::text('name',$cate->name)}}</p>
                         <p class="input_txt"> <span>{{Form::label('desc','描述：')}}</span> {{Form::textarea('desc',$cate->desc)}}</p>
                        <div>
                            {{Form::submit('添加',array('class'=>'btn'))}}
                        </div>
                         <div class="clear"></div>
                    {{Form::close()}}
            </div>
        </div>
	</div>
</body>
</html>

app/views/cate/index.blade.php
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>文章首页</title>
{{HTML::script('js/jquery.js')}}
{{HTML::script('js/navbar.js')}}
<script>
$(function(){
    //点击提示框消失
        $(".success").click(function(){
            $(this).fadeOut(2000);
        });
         $(".error").click(function(){
                    $(this).fadeOut(2000);
                });
})
</script>
{{HTML::script('js/artDialog.js')}}
{{HTML::script("js/cf.js")}}
{{HTML::style("css/artDialog.css")}}
{{HTML::style("css/cate.css")}}
</head>
<body>
    <div class="main">
           <div class="top_nav">
                <div class="top_nav_l"> <b class="index"></b>分类列表 <span>/</span>{{link_to_route('articles.index','首页')}}</div>
                <div class="top_nav_r">{{Auth::user()->username}}  {{link_to_route('logout','退出')}}</div>
                <div style="clear:both"></div>
           </div>
            <!--成功提示-->
                 @if(Session::has('message'))
                    <div class="success">{{Session::get('message')}}</div>
                    @endif
            <!--错误提示-->
                 @if(Session::has('error'))
                    <div class="error">{{Session::get('error')}}</div>
                    @endif
                    @include('navbar')
        <div class="content">

                 <table cellpadding="1" cellspacing="0">
                               <tr>
                                 <th>分类Id</th>
                                 <th>分类标题</th>
                                  <th>所属作者</th>
                                 <th>分类描述</th>
                                  <th colspan="2">编辑操作</th>
                               </tr>

                               @foreach ($cate as $cat)
                                 <tr>
                                   <td>{{ $cat->id }}</td>
                                   <td>{{$cat->name}} <span>({{$cat->count}})</span></td>
                                   <td>{{ Auth::user()->username }}</td>
                                   <td>{{ $cat->desc }}</td>
                                   <td>
                                    {{link_to_route('cate.edit','',$cat->id,array('class'=>'edit'))}}
                                   {{link_to_route('cate.del','',$cat->id,array('class'=>'del'))}}
                                   </td>
                                 </tr>
                               @endforeach
                               @if(count($cate)==0)
                               <tr><td colspan="5">对不起！暂时没有文章！</td></tr>
                               @endif
                 </table>
                 <div class="con_foot">

                    <div class="create">
                    {{ link_to_route('cate.create', '创建分类') }}
                    </div>
                     <div class="page">
                        <!--<a href="#">1</a><a href="#">2</a><a href="#">3</a><a href="#">4</a>-->
                            {{$cate->links()}}
                     </div>
                     <div style="clear: both"></div>
                 </div>


        </div>

    </div>

</body>
</html>